config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  
  # Defines the root path route ("/")
  root "welcome#index"
  get "my_portfolio", to: "users#my_portfolio"
  get "search_stock", to: "stocks#search_stock"
  get "my_stocks", to: "users#my_stocks"
  get "new_stock", to: "stocks#new"
  get "my_friends", to: "users#my_friends"
  resources :user_stocks
  resources :friendship, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: 'User'
end

app/models/stock.rb
class Stock < ApplicationRecord
  has_many :user_stocks
  has_many :users, through: :user_stocks

  validates :name, :ticker, presence: true

  def self.new_lookup(ticker_symbol)
    client = IEX::Api::Client.new(
      publishable_token: Rails.application.credentials.iex_client[:sandbox_api_key],
      endpoint: 'https://sandbox.iexapis.com/v1'
    )
    begin
      new(ticker: ticker_symbol, 
      name: client.company(ticker_symbol).company_name, 
      last_price: client.price(ticker_symbol))
    rescue => exception
      return nil
    end
  end

  def self.check_db(ticker_symbol)
    where(ticker: ticker_symbol).first
  end
end

# Path: app/models/user_stock.rb
class UserStock < ApplicationRecord
  belongs_to :user
  belongs_to :stock
end

# Path: app/models/user.rb
class User < ApplicationRecord
  has_many :user_stocks
  has_many :stocks, through: :user_stocks
  has_many :friendships
  has_many :friends, through: :friendships

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def stock_already_tracked?(ticker_symbol)
    stock = Stock.check_db(ticker_symbol)
    return false unless stock
    stocks.where(id: stock.id).exists?
  end

  def under_stock_limit?
    stocks.count < 10
  end

  def can_track_stock?(ticker_symbol)
    under_stock_limit? && !stock_already_tracked?(ticker_symbol)
  end

  def full_name
    return "#{first_name} #{last_name}" if first_name || last_name
    "Anonymous"
  end

  def self.search(param)
    param.strip!
    to_send_back = (first_name_matches(param) + last_name_matches(param) + email_matches(param)).uniq
    return nil unless to_send_back
    to_send_back
  end

  def self.first_name_matches(param)
    matches('first_name', param)
  end

  def self.last_name_matches(param)
    matches('last_name', param)
  end

  def self.email_matches(param)
    matches('email', param)
  end

  def self.matches(field_name, param)
    where("#{field_name} like ?", "%#{param}%")
  end

  def except_current_user(users)
    users.reject { |user| user.id == self.id }
  end

  def not_friends_with?(id_of_friend)
    !self.friends.where(id: id_of_friend).exists?
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_stocks
  has_many :stocks, through: :user_stocks, dependent: :destroy
  has_many :friendships
  has_many :friends, through: :friendships
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  def stock_already_tracked?(ticker_symbol)
    stock = Stock.check_db(ticker_symbol)
    return false unless stock
    stocks.where(id: stock.id).exists?
  end

  def under_stock_limit?
    stocks.count < 10
  end

  def can_track_stock?(ticker_symbol)
    under_stock_limit? && !stock_already_tracked?(ticker_symbol)
  end

  def full_name
    return "#{first_name} #{last_name}" if (first_name || last_name)
    "Anonymous"
  end

end

app/models/user_stock.rb
class UserStock < ApplicationRecord
  belongs_to :user
  belongs_to :stock
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:index]
  before_action :configure_permitted_parameters, if: :devise_controller?
  
    protected
  
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
      devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
    end

end

app/controllers/friendship_controller.rb
class FriendshipController < ApplicationController

  def show
    @friendship = current_user.friendships.where(friend_id: params[:id]).first
    @friendship.destroy
    flash[:notice] = "Friend was successfully removed"
    redirect_to my_friends_path
  end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController

  def search_stock
    if params[:stock].present?
      @stock = Stock.new_lookup(params[:stock])
      if @stock
        render 'users/my_portfolio'
      else
        flash[:alert] = "Please enter a valid symbol to search"
        redirect_to my_portfolio_path
      end
    else
      flash[:alert] = "Please enter a symbol to search"
      redirect_to my_portfolio_path
    end
  end

  def create
    @stock = Stock(params[:ticker])
    if @stock.save
      current_user.stocks << @stock
      flash[:notice] = "#{@stock.name} was successfully added to your portfolio"
      redirect_to my_stocks_path
    else
      flash[:alert] = "Something went wrong with the stock search process"
      redirect_to my_stocks_path
    end
  end
end

app/controllers/turbo_devise_controller.rb
class TurboDeviseController < ApplicationController
  class Responder < ActionController::Responder
    def to_turbo_stream
      controller.render(options.merge(formats: :html))
    rescue ActionView::MissingTemplate => error
      if get?
        raise error
      elsif has_errors? && default_action
        render rendering_options.merge(formats: :html, status: :unprocessable_entity)
      else
        redirect_to navigation_location
      end
    end
  end

  self.responder = Responder
  respond_to :html, :turbo_stream
end

app/controllers/user_stocks_controller.rb
class UserStocksController < ApplicationController

  def index
    stock = Stock.check_db(params[:ticker])
    if stock.blank?
      stock = Stock.new_lookup(params[:ticker])
    end
    if current_user.can_track_stock?(stock)
      @user_stock = UserStock.create(user: current_user, stock: stock)
      flash[:notice] = "Stock #{params[:ticker]} was successfully added to your portfolio"
      redirect_to my_stocks_path
    else
      flash[:alert] = "You can't track this stock"
      redirect_to my_portfolio_path
    end
  end

  def show
    stock = Stock.find(params[:id])
    user_stock = UserStock.where(user_id: current_user.id, stock_id: stock.id).first
    user_stock.destroy
    flash[:notice] = "#{stock.ticker} was successfully removed from your portfolio"
    redirect_to my_stocks_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def my_stocks
    @tracked_stocks = current_user.stocks
  end

  def my_friends
    @friends = current_user.friends
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_stocks_helper.rb
module UserStocksHelper
end

app/views/layouts/_flash.html.erb
<div class="container">
  <% flash.each do |name, msg| %>
    <div class="alert alert-dismissible fade show alert-<%= name == "notice" ? "success" : "danger" %>">
      <%= msg %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  <% end %>
</div>
 

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <%= link_to "FinanceTracker", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <% if user_signed_in? %>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <% if request.path == my_portfolio_path %>
              <%= link_to "My Portfolio", my_portfolio_path, class: "nav-link active" %>
            <% else %>
              <%= link_to "My Portfolio", my_portfolio_path, class: "nav-link" %>
            <% end %>
          </li>
          <li class="nav-item">
            <% if request.path == my_stocks_path %>
              <%= link_to "My Stocks", my_stocks_path, class: "nav-link active" %>
            <% else %>
              <%= link_to "My Stocks", my_stocks_path, class: "nav-link" %>
            <% end %>
          </li>
          <li class="nav-item">
            <% if request.path == my_friends_path %>
              <%= link_to "My Friends", my_friends_path, class: "nav-link active" %>
            <% else %>
              <%= link_to "My Friends", my_friends_path, class: "nav-link" %>
            <% end %>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Profile
            </a>
            <ul class="dropdown-menu">
              <li>
                <%= link_to edit_user_registration_path, class: "dropdown-item" do %>
                  <i class="bi bi-pencil-square"></i>
                  Edit Profile
                <% end %>
              </li>
              <li><a class="dropdown-item" href="#">Another action</a></li>
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="#">Something else here</a></li>
            </ul>
          </li>
        </ul>
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="navbar-brand" href="#">
              <i class="bi bi-person-circle"></i>
              <%= current_user.full_name %>
            </a>
          </li>
          <li class="nav-item">
            <%= button_to "Sign Out", destroy_user_session_path, method: :delete, class: "btn btn-outline-danger me-2" %>
          </li>
        </ul>
        <form class="d-flex" role="search">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
      </div>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FinanceTracker704</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <!-- Latest compiled and minified CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- Latest compiled JavaScript -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
  </head>

  <body>
    <%= render partial: "layouts/navbar" %>
    <%= render partial: "layouts/flash" %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/stocks/my_portfolio.html.erb
<div class='row'>
  <header class="d-flex flex-wrap justify-content-center py-3 mb-4 border-bottom">
  <a href="#" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-dark text-decoration-none">
        <span class="fs-4">My Portfolio</span>
  </a>
</header>
</div>
<div class='row'>
  <div class='col-12'>
    <%= render partial: 'stocks/stock_search_form' %>
  </div>
</div>


<%= render partial: 'stocks/result' %>

app/views/users/_my_stocks.html.erb
<% if current_user.stocks.any? %>
  <div class='row'>
    <div class='col-8'>
      <table class="table table-striped table-hover">
        <thead>
          <tr>
            <th scope="col">Ticker</th>
            <th scope="col">Name</th>
            <th scope="col">Price</th>
            <th scope="col">Actions</th>
          </tr>
        </thead>
        <tbody>
          <% @tracked_stocks.each do |stock| %>
            <tr>
              <th scope="row"><%= stock.ticker %></th>
              <th scope="row"><%= stock.name %></th>
              <th scope="row"><%= stock.last_price %></th>
              <th scope="row"><%= 'Action placeholder' %></th>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
<% end %>
`

app/views/users/_result.html.erb
<% if @stock %>
  <div class="input-group flex-nowrap">
    <div class="card card-header d-block col-8">
      <strong>Stock: </strong> <%= @stock.name %>
      <strong>Ticker: </strong> <%= @stock.ticker %>
      <strong>Price: </strong> <%= @stock.last_price %>
    </div>
    <div class="input-group flex-nowrap">
      <div class="col-4">
        <% if current_user.can_track_stock?(@stock.ticker) %>
          <%= link_to "save",
            user_stocks_path(user: current_user, ticker: @stock.ticker),
            method: :post,
            class: "btn btn-primary"
          %>
        <% else %>
          <button type="button" class="btn btn-primary position-relative">
            Inbox
            <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger">
              You are already tracking
              <% if !current_user.under_stock_limit? %>
                10 stocks limit reached
              <% end %>
              <span class="visually-hidden">unread messages</span>
              <% if current_user.stock_already_tracked?(@stock.ticker) %>
                this stock
              <% end %>
            </span>
          </button>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/users/_stock_search_form.html.erb
<div class="input-group flex-nowrap">
    <%= form_tag search_stock_path, class: 'input-group flex-nowrap', method: :get do %>
      <div class="col-8">
        <%= text_field_tag :stock, 
          params[:stock],
          placeholder: "Stock ticker symbol", 
          autofocus: true, 
          class: "form-control"
        %>
      </div>
      <div class="col-4">
        <%= button_tag type: :submit, class: 'btn btn-primary' do %>
           <i class="bi bi-search"></i>
        <% end %>
      </div>
    <% end %>
</div>

app/views/users/my_friends.html.erb
<div class='row'>
  <header class="d-flex flex-wrap justify-content-center py-3 mb-4 border-bottom">
    <a href="#" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-dark text-decoration-none">
      <span class="fs-4">My Friends</span>
    </a>
  </header>
</div>
<% if current_user.friends.any? %>
  <div class='row'>
    <div class='col-8'>
      <table class="table table-striped table-hover">
        <thead>
          <tr>
            <th scope="col">Id</th>
            <th scope="col">Email</th>
            <th scope="col">First Name</th>
            <th scope="col">Last Name</th>
            <th scope="col">Actions</th>
          </tr>
        </thead>
        <tbody>
          <% @friends.each do |friend| %>
            <tr>
              <th scope="row"><%= friend.id %></th>
              <th scope="row"><%= friend.email %></th>
              <th scope="row"><%= friend.first_name %></th>
              <th scope="row"><%= friend.last_name %></th>
              <th scope="row">
                <%= link_to "Stop Following",
                  friendship_path(friend),
                  data: { confirm: "Are you sure?" },
                  class: "btn btn-warning"
                %>
              </th>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
<% end %>

app/views/users/my_portfolio.html.erb
<div class='row'>
  <header class="d-flex flex-wrap justify-content-center py-3 mb-4 border-bottom">
    <a href="#" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-dark text-decoration-none">
      <span class="fs-4">My Portfolio</span>
    </a>
  </header>
</div>

<div class='row mb-3'>
  <div class='col-12'>
    <%= render partial: 'users/stock_search_form' %>
  </div>
</div>

<%= render partial: 'users/result' %>
<%# render partial: 'users/my_stocks' %>

app/views/users/my_stocks.html.erb
<div class='row'>
  <header class="d-flex flex-wrap justify-content-center py-3 mb-4 border-bottom">
    <a href="#" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-dark text-decoration-none">
      <span class="fs-4">My Stocks</span>
    </a>
  </header>
</div>
<% if current_user.stocks.any? %>
  <div class='row'>
    <div class='col-8'>
      <table class="table table-striped table-hover">
        <thead>
          <tr>
            <th scope="col">Stock</th>
            <th scope="col">Name</th>
            <th scope="col">Price</th>
            <th scope="col">Actions</th>
          </tr>
        </thead>
        <tbody>
          <% @tracked_stocks.each do |stock| %>
            <tr>
              <th scope="row"><%= stock.ticker %></th>
              <th scope="row"><%= stock.name %></th>
              <th scope="row"><%= stock.last_price %></th>
              <th scope="row">
                <%= link_to "Remove", 
                  user_stock_path(stock), 
                  method: :delete,
                  data: { confirm: "Are you sure?" },
                  class: "btn btn-warning"
                %>
              </th>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
<% end %>

app/views/welcome/index.html.erb
 <div class="px-4 py-5 my-5 text-center">
    <svg xmlns="http://www.w3.org/2000/svg" width="72" height="72" fill="currentColor" class="bi bi-bank" viewBox="0 0 16 16">
      <path d="m8 0 6.61 3h.89a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-.5.5H15v7a.5.5 0 0 1 .485.38l.5 2a.498.498 0 0 1-.485.62H.5a.498.498 0 0 1-.485-.62l.5-2A.501.501 0 0 1 1 13V6H.5a.5.5 0 0 1-.5-.5v-2A.5.5 0 0 1 .5 3h.89L8 0ZM3.777 3h8.447L8 1 3.777 3ZM2 6v7h1V6H2Zm2 0v7h2.5V6H4Zm3.5 0v7h1V6h-1Zm2 0v7H12V6H9.5ZM13 6v7h1V6h-1Zm2-1V4H1v1h14Zm-.39 9H1.39l-.25 1h13.72l-.25-1Z"/>
    </svg>
    <h1 class="display-5 fw-bold">Finance Tracker App</h1>
    <div class="col-lg-6 mx-auto">
      <p class="lead mb-4">
        This app is consuming the IEX API to find stocks.
        Users can create an account and login using Devise for authentication, add stocks to their 
        portfolio and track them, search for stocks and add them to their portfolio.
        users can see their portfolio and the stocks they are tracking.
      </p>
      <div class="d-grid gap-2 d-sm-flex justify-content-sm-center">
        <%= link_to "Sign In", new_user_session_path, type: "button", class: "btn btn-primary btn-lg px-4 gap-3" %>
        <%= link_to "Sign Up", new_user_registration_path, type: "button", class: "btn btn-outline-secondary btn-lg px-4" %>
      </div>
    </div>
  </div>